services:
  cup:
    image: ghcr.io/sergi0g/cup
    container_name: cup
    command: serve
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.services.cup.loadbalancer.server.port: "8000"
      traefik.http.routers.cup.entrypoints: "https"
      traefik.http.routers.cup.rule: "Host(`${FQDN}`)"
      traefik.http.routers.cup.middlewares: "oidc-auth@file"
networks:
  proxy:
    external: true
