services:
  rustfs:
    image: rustfs/rustfs
    container_name: rustfs
    init: true
    volumes:
      - data:/data
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.services.rustfs.loadbalancer.server.port: "7000"
      traefik.http.routers.rustfs.entrypoints: "https"
      traefik.http.routers.rustfs.rule: "Host(`${FQDN}`)"
volumes:
  data: {}
networks:
  proxy:
    external: true
