rvices:
  sftpgo:
    image: drakkan/sftpgo
    container_name: sftpgo
    init: true
    restart: unless-stopped
    environment:
      - SFTPGO_SFTPD__BINDINGS__0__PORT=2022
    volumes:
      - home:/srv/sftpgo/data
      - backups:/srv/sftpgo/backups
      - config:/var/lib/sftpgo
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.sftpgo.loadbalancer.server.port=8080
      - traefik.http.routers.sftpgo-secure.entrypoints=https
      - traefik.http.routers.sftpgo-secure.rule=Host(`${FQDN}`)
      - traefik.tcp.routers.sftpgo-sftp.entrypoints=sftpgo
      - traefik.tcp.routers.sftpgo-sftp.rule=HostSNI(`*`)
      - traefik.tcp.services.sftpgo-sftp.loadbalancer.server.port=2022

volumes:
  home: {}
  backups: {}
  config: {}


networks:
  proxy:
    external: true
