services:
  fb_quantum:
    image: gtstef/filebrowser
    container_name: fb_quantum
    init: true
    restart: unless-stopped
    networks:
      - proxy
    environment:
      FILEBROWSER_CONFIG: "${FILEBROWSER_CONFIG}"
      FILEBROWSER_ADMIN_PASSWORD: "${FILEBROWSER_ADMIN_PASSWORD}"
      TZ: "Europe/Madrid"
    labels:
      traefik.enable: "true"
      traefik.http.services.quantum.loadbalancer.server.port: "80"
      traefik.http.routers.quantum.entrypoints: "https"
      traefik.http.routers.quantum.rule: "Host(`${FQDN}`)"
networks:
  proxy:
    external: true
